### PR TITLE
fully transition to pyproject

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Review by mikegerber — APPROVED** [review]
- Personally, I would just delete `setup.py` (but we have a discussion about that in Gitter)
- Use of setuptools-ocrd looks good now.

I haven't actually tested if it builds, but LGTM

**Review by cneud — APPROVED** [review]
Works for me, thx!

**Comment by kba** [comment]
I've removed the `setup.py`, like @mikegerber suggested and as discussed today. There is really no benefit of being backwards-compatible with outdated build methods.

**Comment by cneud** [comment]
> I've removed the setup.py, like @mikegerber suggested

Agreed! Any idea why the test is failing now though?

**Comment by kba** [comment]
> Any idea why the test is failing now though?

Intermittent issue with the cache in GHA. Restarted, tests pass.

**Pull request merged**
