### PR TITLE
non-legacy namespace package

### PR DESCRIPTION
**Pull request by bertsky**
The current legacy approach to namespace packaging does not work with development/editable installation. See OCR-D/ocrd_all#433

This PR fixes it for this package – analogous PRs to the other qurator repos will follow.

### CODE REVIEW

**Comment by vahidrezanezhad** [comment]
@bertsky
This pr fails with the following error for stand-alone eynollah:

`    from qurator.eynollah.cli import main  `
`   ModuleNotFoundError: No module named 'qurator'  `

**Comment by bertsky** [comment]
Indeed. I thought I had tested thoroughly. For the moment I'm puzzled.

**Comment by bertsky** [comment]
The strangest thing of all is that these imports actually _do work_, but not in the entrypoint:
```python
>>> from qurator.eynollah.cli import main
>>> main
<Command main>
```

    python -c "from qurator.eynollah.cli import main; main()" --help

```
Usage: -c [OPTIONS]

Options:
  -i, --image FILE                image filename
  -o, --out DIRECTORY             directory to write output xml data
                                  [required]
  -di, --dir_in DIRECTORY         directory of images
...
```

**Comment by bertsky** [comment]
ah, found it – will need to update the other PRs as well ...

**Review by vahidrezanezhad — APPROVED** [review]

**Comment by bertsky** [comment]
I just tried afresh (new clone, new venv) from main.

With `pip install -e . && python -c "import qurator.eynollah"` it works.

With `pip uninstall eynollah && pip install . && python -c "import qurator.eynollah"` it also works.

> eynollah still fails to find the qurator module

Perhaps you have some of the other packages in `qurator` namespace installed **without merging my PR** so you end up with a mix of old and new style namespace packages again?

**Comment by vahidrezanezhad** [comment]
Yes you are right. With pip install -e . works. Thank you.

**Pull request merged**
