### PR TITLE
use PEP420 style qurator namespace

### PR DESCRIPTION
**Pull request by kba**
Draft so we can avoid the problems experienced in https://github.com/qurator-spk/dinglehopper/issues/76

### CODE REVIEW

**Comment by cneud** [comment]
Many thanks! This is up on the TODO List, also for https://github.com/qurator-spk/sbb_binarization/issues/50.

**Comment by cneud** [comment]
(CI fails for 3.8 until https://github.com/qurator-spk/eynollah/pull/91 is merged)

**Review by cneud — APPROVED** [review]

**Review by vahidrezanezhad — APPROVED** [review]

**Comment by kba** [comment]
CI fails for 3.8 with `ValueError: bad marshal data (unknown type code)` (https://app.circleci.com/pipelines/github/qurator-spk/eynollah/255/workflows/2e29af30-f9fa-4b0e-9d00-a8ad8c1a6a7f/jobs/267) - what is this about?

**Comment by cneud** [comment]
This is due to [Keras model format using some native Python serialization which is version dependent](https://github.com/qurator-spk/sbb_binarization/issues/39#issuecomment-1273900673) and was fixed by https://github.com/qurator-spk/eynollah/pull/91 but I believe the CI cache still has the models in the old HDF5 format...

**Comment by kba** [comment]
> This is due to [Keras model format using some native Python serialization which is version dependent](https://github.com/qurator-spk/sbb_binarization/issues/39#issuecomment-1273900673) and was fixed by #91 but I believe the CI cache still has the models in the old HDF5 format. So we need to figure out #98...

Ha, sorry, forgot that was the issue, thanks.

**Pull request merged**
